### ISSUE TITLE
How to use disposable list only?

### ISSUE THREAD

**Issue by 200-0K** [erlandmuchasaj/laravel-email-verify#1]
How can I use only a disposable list without relying on a service? Setting `INDISPOSABLE_ENABLED` to `false` doesn't seem to resolve the issue. Awesome package BTW :)

**Comment by erlandmuchasaj** [comment]
That is correct, indisposable will enable/disable the package, maybe i will add a new configuration so you can enable list/service/both

**Comment by erlandmuchasaj** [comment]
@200-0K  I added a configuration: `INDISPOSABLE_USE_SERVICE` which by default is `true` if you make it false, it will skip the service call. and use a blacklist of disposable emails.
